CREATE TABLE IF NOT EXISTS users (
    id BIGINT PRIMARY KEY,
    display_name VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    phone_number VARCHAR(15),
    password VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    role VARCHAR(50) NOT NULL,
    enabled BOOLEAN DEFAULT TRUE
);
